export const DATA = [
    {
      title: "Must Do Today",
      task1: "Write blog post on Next.js performance tips",
      task2: "Fix bugs in the MCP server repo",
      task3: "Push Docker config updates to GitHub",
      background: "rgb(159, 103, 158)",
      accent: "rgb(255, 233, 245)",
    },
    {
      title: "This Week Goals",
      task1: "Redesign the portfolio landing page",
      task2: "Publish NPM package for custom hooks",
      task3: "Record tutorial video on Tailwind + React",
      background: "rgb(103, 119, 159)",
      accent: "rgb(228, 235, 255)",
    },
    {
      title: "Upcoming Projects",
      task1: "Prototype chat app with Supabase",
      task2: "Experiment with Rust for a new API",
      task3: "Set up CI/CD with GitHub Actions",
      background: "rgb(159, 134, 103)",
      accent: "rgb(255, 243, 225)",
    },
    {
      title: "Maintenance Tasks",
      task1: "Refactor old components in dashboard app",
      task2: "Audit dependencies for security updates",
      task3: "Delete unused branches in Git repositories",
      background: "rgb(103, 159, 121)",
      accent: "rgb(230, 255, 238)",
    },
    {
      title: "Learning & Research",
      task1: "Read about React Server Components",
      task2: "Try building a full-stack app with Remix",
      task3: "Explore edge functions on Vercel",
      background: "rgb(159, 103, 103)",
      accent: "rgb(255, 230, 230)",
    },
    {
      title: "Community & Content",
      task1: "Respond to GitHub issues on open source repo",
      task2: "Plan next Dev.to article outline",
      task3: "Record YouTube video walkthrough of recent project",
      background: "rgb(121, 103, 159)",
      accent: "rgb(237, 230, 255)",
    },
    {
      title: "Creative Work",
      task1: "Design a new illustration for portfolio",
      task2: "Create a new UI kit for design system",
      task3: "Develop an animation for personal website",
      background: "rgb(103, 134, 159)",
      accent: "rgb(230, 255, 240)",
    },
    {
      title: "Workshops & Speaking",
      task1: "Prepare slides for React conference talk",
      task2: "Host a workshop on modern JavaScript features",
      task3: "Submit a proposal for front-end development summit",
      background: "rgb(159, 121, 103)",
      accent: "rgb(255, 245, 225)",
    },
    {
      title: "Team Collaboration",
      task1: "Organize team meeting for next sprint planning",
      task2: "Review pull requests for project repository",
      task3: "Collaborate on new feature development for app",
      background: "rgb(103, 159, 179)",
      accent: "rgb(230, 255, 255)",
    },
    {
      title: "Networking & Growth",
      task1: "Connect with professionals on LinkedIn",
      task2: "Attend a virtual meetup on web development",
      task3: "Start a mentorship relationship with a junior developer",
      background: "rgb(159, 103, 121)",
      accent: "rgb(245, 230, 230)",
    },
    {
      title: "Personal Development",
      task1: "Practice mindfulness meditation for 10 minutes",
      task2: "Take an online course on productivity",
      task3: "Read a book on growth mindset",
      background: "rgb(121, 159, 103)",
      accent: "rgb(230, 255, 230)",
    },
    {
      title: "Health & Fitness",
      task1: "Go for a 30-minute jog",
      task2: "Prepare healthy meals for the week",
      task3: "Schedule a check-up with the doctor",
      background: "rgb(103, 159, 134)",
      accent: "rgb(240, 255, 230)",
    },
    {
      title: "Financial Management",
      task1: "Review monthly budget and expenses",
      task2: "Invest in a new stock or ETF",
      task3: "Save for a big purchase or vacation",
      background: "rgb(159, 103, 159)",
      accent: "rgb(230, 225, 255)",
    },
    {
      title: "Home Improvement",
      task1: "Clean and organize the garage",
      task2: "Fix leaky faucet in the kitchen",
      task3: "Paint the living room walls",
      background: "rgb(103, 121, 159)",
      accent: "rgb(255, 230, 255)",
    },
    {
      title: "Travel Plans",
      task1: "Research destination options for next vacation",
      task2: "Book flight tickets for the trip",
      task3: "Create an itinerary for travel activities",
      background: "rgb(159, 103, 134)",
      accent: "rgb(255, 243, 245)",
    },
    {
      title: "Social Events",
      task1: "Plan weekend get-together with friends",
      task2: "Attend a family reunion gathering",
      task3: "Host a game night with neighbors",
      background: "rgb(134, 159, 103)",
      accent: "rgb(245, 255, 230)",
    },
    {
      title: "Hobbies & Interests",
      task1: "Learn to play a new musical instrument",
      task2: "Start a new painting or art project",
      task3: "Join an online book club",
      background: "rgb(159, 134, 103)",
      accent: "rgb(255, 230, 230)",
    },
    {
      title: "Family Time",
      task1: "Organize a family outing for the weekend",
      task2: "Help kids with homework",
      task3: "Plan a surprise gift for a family member",
      background: "rgb(103, 159, 179)",
      accent: "rgb(230, 255, 255)",
    },
    {
      title: "Charity & Volunteering",
      task1: "Volunteer at the local food bank",
      task2: "Organize a charity drive for donations",
      task3: "Contribute to a cause by donating online",
      background: "rgb(121, 159, 134)",
      accent: "rgb(245, 230, 255)",
    },
    {
      title: "Home Improvement",
      task1: "Clean and organize the garage",
      task2: "Fix leaky faucet in the kitchen",
      task3: "Paint the living room walls",
      background: "rgb(103, 121, 159)",
      accent: "rgb(255, 230, 255)",
    },
  ];